finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("finches/", views.finches_index, name="index"),
    path("finches/<int:finch_id>/", views.finches_detail, name="detail"),
    path("finches/create/", views.FinchCreate.as_view(), name="finches_create"),
    path("finches/<int:pk>/update/", views.FinchUpdate.as_view(), name="finches_update"),
    path("finches/<int:finch_id>/delete/", views.finches_delete, name="finches_delete"),
    path("finches/<int:finch_id>/add_feeding", views.add_feeding, name="add_feeding"),
    path('finches/<int:finch_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('finches/<int:finch_id>/unassoc_toy/<int:toy_id>/', views.unassoc_toy, name='unassoc_toy'),
    path("toys/", views.ToyList.as_view(), name="toys_index"),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path("toys/create", views.ToyCreate.as_view(), name="toys_create"),
]

main_app/models.py
from django.db import models

from django.urls import reverse

from datetime import date

MEALS = (
    ("B", "Breakfast"),
    ("L", "Lunch"),
    ("D", "Dinner")
)

# Create your models here.

class Toy(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=30)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("toys_detail", kwargs={'pk': self.id})
    

class Finch(models.Model):
    breed = models.CharField(max_length=50)
    wingspan = models.CharField(max_length=50)
    colors = models.CharField(max_length=50)

    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return self.breed

    def get_absolute_url(self):
        return reverse("detail", kwargs={'finch_id': self.id})
    
    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >= len(MEALS)


class Feeding(models.Model):
    date = models.DateField("Feeding Date")
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
        )
    
    finch = models.ForeignKey(
        Finch,
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ["-date"]

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .models import Finch, Toy

from .forms import FeedingForm

# finches = [
#   {'breed': 'European Goldfinch', 'wingspan': '21cm to 25.5cm', 'colors': "red, black, yellow"},
#   {'breed': 'Chaffinch', 'wingspan': '26cm', 'colors': "grey, brown, yellow"},
#   {'breed': 'Greenfinch', 'wingspan': '21cm to 25.5cm', 'colors': "grey, black, yellow"},
#   {'breed': 'Linnet', 'wingspan': '21cm to 25.5cm', 'colors': "red, brown, grey"},
# ]

# Create your views here.
def home(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

def finches_index(request):
    finches = Finch.objects.all()
    return render(request, "finches/index.html", {
        "finches": finches
    })

def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)

    id_list = finch.toys.all().values_list("id")

    toys_finch_deosnt_have = Toy.objects.exclude(id__in=id_list)

    feeding_form = FeedingForm()

    return render(request, "finches/detail.html", { 'finch' : finch, 'feeding_form': feeding_form, 'toys': toys_finch_deosnt_have})

class FinchCreate(CreateView):
    model = Finch
    fields = "__all__"

class FinchUpdate(UpdateView):
    model = Finch
    fields = ['wingspan', 'colors']

class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches'


def finches_delete(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    finch.delete()
    return redirect('index')

def add_feeding(request, finch_id):
    # Create a modelForm instance using the data that was submitted in the form
    form = FeedingForm(request.POST)

    # Validate the form
    if form.is_valid():
        # Don't save the form to the DB until it has the finch_id assigned
        new_feeding = form.save(commit=False)
        new_feeding.finch_id = finch_id
        new_feeding.save()
    return redirect('detail', finch_id=finch_id)

class ToyList(ListView):
    model = Toy

class ToyDetail(DetailView):
  model = Toy

class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'


def assoc_toy(request, finch_id, toy_id):
    Finch.objects.get(id=finch_id).toys.add(toy_id)
    return redirect('detail', finch_id=finch_id)

def unassoc_toy(request, finch_id, toy_id):
    Finch.objects.get(id=finch_id).toys.remove(toy_id)
    return redirect('detail', finch_id=finch_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector</h1>
<hr>
<p>You can see many many beautiful finches here</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Finch Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo"
                >&nbsp;&nbsp;Finch Collector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'index' %}">All Finches</a></li>
            <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
            <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
            <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div>All Rights Reserved, &copy; 2023 Finch Collector</div>
    </footer>
  </body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="car-title">{{ finch.breed }}</span>
        <p>Wingspan: {{ finch.wingspan }}</p>
        <p>Colors: {{ finch.colors }}</p>
      </div>

      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}" class="btn">EDIT</a>

        <form action="{% url 'finches_delete' finch.id %}" method="POST">
          {% csrf_token %}
          <input
            type="submit"
            class="btn"
            value="DELETE"
            onclick="return confirm('Delete this finch?')"
          />
        </form>
      </div>
    </div>
  </div>

  <div class="col s6">
    <!-- Add Feeding button -->
    <form action="{% url 'add_feeding' finch.id %}" method="POST">
      {% csrf_token %} {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding" />
    </form>

    <!-- Fed for Today -->
    {% if finch.fed_for_today %}
    <div class="card-panel teal-text center-align">
      {{ finch.breed }} has been fed all meals for today
    </div>
    {% else %}
    <div class="card-panel teal-text center-align">
      {{ finch.breed }} might be hungry
    </div>
    {% endif %}

    <!-- Feeding History -->
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
        <tr>
          <td>{{ feeding.date }}</td>
          <td>{{ feeding.get_meal_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
    <div class="col s6">
        <h3>{{ finch.breed }}'s Toys</h3>
        {% if finch.toys.count %} {% for toy in finch.toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                  </span>
            </div>
            <div class="card-action">
                <form action="{% url 'unassoc_toy' finch.id toy.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Remove</button>
                </form>
            </div>
        </div>
        {% endfor %} {% else %}
            <h5>No Toys 😿</h5>
        {% endif %}
    </div>

<div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
        {% for toy in toys.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_toy' finch.id toy.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h5>{{finch.breed}} Already Has All Toys Available</h5>
    {% endif %}
</div>
</div>

  <script>
    const dateEl = document.getElementById("id_date");
    // M is Materialize's global variable
    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });

    const selectEl = document.getElementById("id_meal");
    M.FormSelect.init(selectEl);
  </script>

  {% endblock %}
</div>

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
<a href="{% url 'detail' finch.id %}">
    <div class="card">
        <div class="card-content">
            <span class="car-title">{{ finch.breed }}</span>
        </div>
    </div>
</a>
{% endfor %}



{% endblock%}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

    <h1>HOME</h1>

{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.breed }}</span></h1>
{% else %}
    <h1>Add a new finch</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Toy</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>

{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %} {% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
<a href="{% url 'toys_detail' toy.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ toy.name }}</span>
      <p>Color: {{ toy.color }}</p>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}